[package]
name = "ideal"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 2

[dependencies]
ariadne = "0.4.1"
chumsky = { git = "https://github.com/zesterer/chumsky.git", default-features = false, features = ["std", "label"] }
